services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    environment:
      - API_SPEC=./openapi-spec/openapi.yaml
      - NODE_ENV=production
    depends_on:
      backend:
        condition: service_healthy
    develop:
      watch:
        - path: app/frontend
          action: sync+restart
          target: /app
        - path: app/frontend/node_modules
          action: rebuild
          target: /app/node_modules
        - path: openapi-spec/openapi.yaml
          action: rebuild
          target: /app/openapi-spec/openapi.yaml
    ports:
      - "3000:3000"
    command: >
      bun run dev

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    develop:
      watch:
        - path: app/backend
          action: sync
          target: /app/backend
        - path: openapi-spec/openapi.yaml
          action: rebuild
    depends_on:
      db_init:
        condition: service_completed_successfully
    environment:
      - TABLE_NAME=LocalDevTable
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-west-2
      - DYNAMODB_ENDPOINT=http://localstack:4566
      - IMAGE_BUCKET_NAME=my-bucket
      - COGNITO_USER_POOL_ID=us-west-2_XXXXXXXXX
      - COGNITO_CLIENT_ID=XXXXXXXXXXXXXXXX
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 5s
      timeout: 2s
      retries: 5
  localstack:
    image: localstack/localstack:stable
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - PERSISTENCE=1
    volumes:
      - localstack_data:/var/lib/localstack
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 20s
  db_init:
    build:
      context: app/seed
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-west-2
      - AWS_ENDPOINT=http://localstack:4566
    entrypoint: >
      bun seed.ts

volumes:
  localstack_data:
