---
version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - ./app/client:/usr/src/app
      - /usr/src/app/node_modules
    healthcheck:
      test: curl -s localhost:3000/
      interval: 10s
      timeout: 15s
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_SERVER: "http://localhost:3001"
      REACT_APP_API_BASE_URL: '/v1/heartofvalley'

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      API_BASE_URL: '/v1/heartofvalley'
    volumes:
      - ./app/server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    healthcheck:
      test: curl localhost:3001/v1/heartofvalley/ping
      interval: 10s
      timeout: 15s
