
FROM openapitools/openapi-generator-cli:v7.18.0 AS generate

COPY ./openapi.yaml .

RUN openapi-generator-cli generate -i openapi.yaml -g rust-axum -o /local/openapi

FROM rust:1.92.0-alpine3.23

RUN cargo install cargo-watch

RUN apk add --no-cache curl

COPY ./app/rust-backend /app/rust-backend

COPY --from=generate /local/openapi /app/rust-backend/openapi

WORKDIR /app/rust-backend

CMD ["cargo", "watch", "-x", "run"]