services:
  frontend:
    build:
      context: app/frontend
    volumes:
      - ./app/frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: >
      bun dev

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    environment:
      API_BASE_URL: "/v1/heartofvalley"
    volumes:
      - ./app/server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3001:3001"
    healthcheck:
      test: curl localhost:3001/v1/heartofvalley/ping
      interval: 10s
      timeout: 15s
