FROM golang:1.24-alpine3.22

WORKDIR /app

RUN apk add --no-cache git

RUN go install github.com/air-verse/air@v1.62.0

COPY ./app/backend .

COPY ./openapi.yaml .

RUN apk add --no-cache curl

RUN API_SPEC=./openapi.yaml go generate ./...

RUN go mod tidy