openapi: 3.0.0
info:
  title: heartofthevalley
  description: API for Heart of the Valley
  version: 0.0.1
servers:
  - url: https://s06hks51dl.execute-api.us-west-2.amazonaws.com
    description: Production Server
  - url: http://localhost:8080
    description: Development Server
components:
  schemas:
    Feature:
      type: object
      properties:
        PK:
          type: string
        SK:
          type: string
        address:
          type: string
        artist:
          type: string
        artistUrl:
          type: string
        artType:
          type: string
        city:
          type: string
        description:
          type: string
        enabled:
          type: boolean
        facility:
          type: string
        imagePath:
          type: string
        isActive:
          type: string
        latLong:
          type: array
          items:
            type: string
        partnership:
          type: string
        postalCode:
          type: string
        sourceUrl:
          type: string
        sourceUrlText:
          type: string
        state:
          type: string
        title:
          type: string
    ListFeaturesResponse:
      type: object
      properties:
        features:
          type: array
          items:
            $ref: "#/components/schemas/Feature"
        lastFeatureId:
          type: string
      required:
        - features
paths:
  /features:
    get:
      summary: List features
      operationId: listFeatures
      parameters:
        - name: lastFeatureId
          in: query
          description: The ID of the last evaluated feature for pagination.
          required: false
          schema:
            type: string
        - name: projectionExpression
          in: query
          description: A comma-separated list of attributes to include in the response.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A list of features
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListFeaturesResponse"
  /features/{featureId}:
    get:
      summary: Get a feature by ID
      operationId: getFeatureById
      parameters:
        - name: featureId
          in: path
          description: The ID of the feature to retrieve.
          required: true
          schema:
            type: string
        - name: projectionExpression
          in: query
          description: A comma-separated list of attributes to include in the response.
          required: false
          schema:
            type: string
      responses:
        "200":
          description: A single feature
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feature"
        "404":
          description: Feature not found
