openapi: 3.0.0
info:
  title: heartofthevalley
  description: API for Heart of the Valley
  version: 0.0.1
components:
  schemas:
    Feature:
      $ref: "./schemas/feature.yaml"
    ListFeaturesResponse:
      $ref: "./schemas/list-features-response.yaml"
    ImageUploadRequestBody:
      $ref: "./schemas/image-upload-request-body.yaml"
    ImageUploadResponse:
      $ref: "./schemas/image-upload-response.yaml"
paths:
  /features:
    $ref: "./paths/features.yaml"
  /features/{featureId}:
    $ref: "./paths/features-feature-id.yaml"
  /features/image-url:
    $ref: "./paths/features-image-url.yaml"
