name: Test Pipeline

on:
  pull_request:
    branches:
      - main
      - staging

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: "1.2.19"

      - name: Install dependencies
        run: |
          cd app/deployment
          bun install

      - name: Run tests
        run: |
          cd app/deployment
          bun test
