name: Deploy Pipeline

on:
  push:
    branches:
      - main
      - infinite-scroll
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: "1.2.19"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::253016134262:role/HeartOfTheValleyStack-HeartOfTheValleyGithubActions-f5vUJwlfoLFr
          aws-region: us-west-2

      - name: Deploy
        run: |
          cd app/deployment
          bun install
          bun run deploy --require-approval never

permissions:
  id-token: write
  contents: read
